;
; File generated by cc65 v 2.15
;
	.fopt		compiler,"cc65 v 2.15"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_memcpy
	.import		_open
	.import		__errno
	.export		_opendir
	.import		__dirread

; ---------------------------------------------------------------
; __near__ struct DIR * __near__ __fastcall__ opendir (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_opendir: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	jsr     push0
	ldy     #$11
	jsr     subysp
	lda     #$24
	ldy     #$04
	sta     (sp),y
	ldy     #$15
	lda     (sp),y
	iny
	ora     (sp),y
	beq     L005B
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	beq     L0051
	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$2E
	bne     L0009
	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	ldx     #$00
	lda     (ptr1),y
	beq     L005B
	bra     L0009
L0051:	tax
L005B:	ldy     #$05
	sta     (sp),y
	bra     L0059
L0009:	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$30
	beq     L0054
	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$31
	beq     L0054
	bra     L0058
L0054:	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$3A
	bne     L0058
	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	beq     L0057
	bra     L0058
L0057:	ldy     #$16
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$05
	sta     (sp),y
	ldx     #$00
	txa
	iny
	sta     (sp),y
	bra     L0059
L0058:	lda     #$07
	bra     L005A
L0059:	lda     #$02
	tay
	jsr     staxysp
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	lda     #$01
	jsr     pusha0
	ldy     #$04
	jsr     _open
	jsr     stax0sp
	txa
	bmi     L0047
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #$15
	jsr     leaa0sp
	jsr     pushax
	lda     #$02
	jsr     __dirread
	tax
	beq     L0047
	ldx     #$00
	lda     #$11
	jsr     _malloc
	ldy     #$11
	jsr     staxysp
	ldy     #$12
	lda     (sp),y
	dey
	ora     (sp),y
	beq     L003F
	iny
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$10
L0046:	lda     (sp),y
	sta     (ptr1),y
	dey
	bpl     L0046
	bra     L0047
L003F:	lda     #$02
L005A:	sta     __errno
	stz     __errno+1
L0047:	ldy     #$12
	jsr     ldaxysp
	ldy     #$17
	jmp     addysp

.endproc

